[workspace]
members = [
    "firmware",
    "hs-probe-bsp",
    "usb-device",
    "usbd-serial",
]

[patch.crates-io]
usb-device = { path = "usb-device" }
usbd-serial = { path = "usbd-serial" }

[profile.release]
debug = true
