[workspace]
members = [
    "firmware",
    "hs-probe-bsp",
    "hs-probe-examples",
    "stm32f7xx-hal",
]

[patch.crates-io]
stm32f7xx-hal = { path = "stm32f7xx-hal" }

[profile.release]
debug = true
