[workspace]
members = [
    "firmware",
    "hs-probe-bsp",
]

[patch.crates-io]
usbd-serial = { git = "https://github.com/Disasm/usbd-serial", rev = "827116e5fab66a51ab7d68774419b0f187b24b90" }

[profile.release]
debug = true
